version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1
  node: circleci/node@5.0.2

jobs:
  prod:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          node-version: "20.9.0"
      - run: "echo Staging deploy!"
      - add_ssh_keys:
          fingerprints:
            - "d5:65:6b:1a:57:05:cc:79:f0:7d:d8:37:c1:25:a8:ed"
      - run: "sudo apt-get update && sudo apt-get install -y rsync"
      - run:
          name: "Install NPM packages"
          command: |
            cd foucault_web_app
            npm install
      - run:
          name: "Build assets"
          command: |
            cd foucault_web_app
            npm run build
      - run:
          name: "Staging deploy"
          command: "rsync -av --delete --exclude-from='rsync-exclude.txt' -e 'ssh -o StrictHostKeychecking=no -p 2222' ~/repo/ pinoko.jp-roughlang@ssh.lolipop.jp:/home/users/2/pinoko.jp-roughlang/web/foucault/prod/foucault-web"
      - run:
          name: "Composer"
          command: "ssh -p 2222 pinoko.jp-roughlang@ssh.lolipop.jp 'cd /home/users/2/pinoko.jp-roughlang/web/foucault/prod/foucault-web/foucault_web_app;/usr/local/php/8.2/bin/php composer.phar update'"
      - run:
          name: "Optimize"
          command: "ssh -p 2222 pinoko.jp-roughlang@ssh.lolipop.jp 'cd /home/users/2/pinoko.jp-roughlang/web/foucault/prod/foucault-web/foucault_web_app;/usr/bin/bash optimizer.sh'"
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy-workflow:
    jobs:
      - prod:
        filters:
          branches:
            only: main
  say-hello-workflow:
    jobs:
      - say-hello
